### ISSUE TITLE
Why is resh listening on my local network?

### ISSUE THREAD

**Issue by GoDzM4TT3O** [curusarn/resh#151]
Running `sudo lsof -i | head` produces the following output:

```
COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME

[Redacted]
[...]

resh-daemon  4151 matteo    5u  IPv4  21267      0t0  TCP localhost:moshebeeri (LISTEN)
```

Why's this?

**Comment by curusarn** [comment]
Resh-daemon should be only listening on the loopback address. 

What version of resh do you have? (You can find that out using this command `reshctl status`)
