### ISSUE TITLE
Question: Is it possible to NOT include directory in search?

### ISSUE THREAD

**Issue by mpilka** [curusarn/resh#153]
Hello,

first of all, thanks for a nice project and all your efforts.

I have been using Resh for 6 months now and found out that more often than not I need a command from my recent history (something I typed just few minutes ago) rather than command from far history (something I typed many times in a particular directory, but a long time ago). However, Resh's suggestions do not list such recent command anywhere close to the top of the list because directory condition "outweighs" timestamp.

Is it possible to NOT include directory in search? Search results would be more appropriate for me.

Thanks,
Martin

**Comment by curusarn** [comment]
When you press `Ctrl+R` the directories and other details are ignored and they also disappear from the interface. Pressing `Ctrl+R` again toggles between the contextual and "raw" non-contextual search.


I hope this helps.  
Simon

**Comment by mpilka** [comment]
Wow, thanks for your fast response. Yeah, it works.

Is this new functionality? I just updated Resh and would swear CTRL+R interface looked different in previous version.

Thanks,
Martin

**Comment by curusarn** [comment]
No problem. I just visited Github at just the right time :D

Depends on what you consider "new". I have been making a lot of changes in resh about 3-4 months ago.
