### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ilyavaiser** [curusarn/resh#163]
Last login: Tue Sep 14 12:46:38 on ttys002
@2020 Portainer % panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/curusarn/resh/pkg/searchapp.leftCutPadString(0xc0003d7ce0, 0x2a, 0xfffffffffffffff3, 0xc000704b30, 0x10)
	/home/runner/work/resh/resh/pkg/searchapp/item.go:249 +0x13d
github.com/curusarn/resh/pkg/searchapp.ItemColumns.ProduceLine(0xc000704b30, 0x10, 0xc000704a00, 0x7, 0xc0006d2dc0, 0x36, 0xc0003d7c80, 0x2d, 0xc0003d7ce0, 0x2a, ...)
	/home/runner/work/resh/resh/pkg/searchapp/item.go:217 +0x1b2
main.manager.normalMode(0x7ffeefbff7c5, 0x24, 0x7ffeefbff7f1, 0x10, 0x7ffeefbff808, 0x35, 0x7ffeefbff850, 0x32, 0xa43, 0x78, ...)
	/home/runner/work/resh/resh/cmd/cli/main.go:517 +0x890
main.manager.Layout(0x7ffeefbff7c5, 0x24, 0x7ffeefbff7f1, 0x10, 0x7ffeefbff808, 0x35, 0x7ffeefbff850, 0x32, 0xa43, 0x78, ...)
	/home/runner/work/resh/resh/cmd/cli/main.go:432 +0x392
github.com/awesome-gocui/gocui.(*Gui).flush(0xc0000b2b40, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/awesome-gocui/gocui@v0.6.0/gui.go:477 +0x348
github.com/awesome-gocui/gocui.(*Gui).MainLoop(0xc0000b2b40, 0x24, 0x7ffeefbff7f1)
	/home/runner/go/pkg/mod/github.com/awesome-gocui/gocui@v0.6.0/gui.go:426 +0x247
main.runReshCli(0x0, 0x0, 0x0)
	/home/runner/work/resh/resh/cmd/cli/main.go:167 +0x1418
main.main()
	/home/runner/work/resh/resh/cmd/cli/main.go:40 +0x26
# RESH SEARCH APP failed - sorry for the inconvinience (error output was saved to ~/.resh/cli_last_run_out.txt)

**Comment by ilyavaiser** [comment]
How I can use this? Need to wait for the release? When?

**Comment by curusarn** [comment]
I will make a new release soon.

**Comment by curusarn** [comment]
I have just released a new version. Can you try if updating solves your issue? (Run `reshctl update` and restart your terminal)

**Comment by curusarn** [comment]
Closing. Feel free to reopen if the issue persists.
