### ISSUE TITLE
Pressing Right arrow key quits , instead of edit

### ISSUE THREAD

**Issue by v3ss0n** [curusarn/resh#166]
Is that a bug?

**Comment by curusarn** [comment]
Hey, that's definitely not intended.

Can you provide a bit more info about your setup:
- What OS are you using?
- What shell version are you using?

**Comment by v3ss0n** [comment]
I think that is intended behavior , the right arrow copys the command to the shell
we are suppose to edit there i guess. 
I was thinking to edit in resh , before going to shell.

**Comment by curusarn** [comment]
Ah, I see. I thought resh just quit without pasting the command.

Sorry for the confusion.

**Comment by curusarn** [comment]
I decided to not reimplement editing inside the resh search because people can have their shell configured in a way they like and I can never replicate that inside the search cli app.
