### ISSUE TITLE
Control + G dosen't paste , it just quits.

### ISSUE THREAD

**Issue by v3ss0n** [curusarn/resh#167]
Seems like only command that works is enter, anyone?
is this abandoned project?

**Comment by curusarn** [comment]
Control+G should take whatever is in the search input and paste it onto the command line. Does it behave differently for you?

**Comment by v3ss0n** [comment]
I got used to it now .
Ctrl + G = Whatever i had typed (not the selected item)
i expect current input inside resh to be replaced by selected item , when ctrl + g is pressed.

**Comment by curusarn** [comment]
That would be also an interesting feature.
Currently, you can achieve that by pressing `arrow right` and then `ctrl + R`.
`arrow right` pastes the selected entry onto the command line. Then `ctrl + R` opens the search app again and the contents on the command line are used as search input. It's a two step process but it's possible.

**Comment by v3ss0n** [comment]
Two steps but it works . I believe the way i expected is to work is a bit better for UX>
