### ISSUE TITLE
use of internal package github.com/curusarn/resh/internal/record not allowed

### ISSUE THREAD

**Issue by tivvit** [curusarn/resh#180]
```
package github.com/tivvit/resh-sync-connector-sqlite
	main.go:5:2: use of internal package github.com/curusarn/resh/internal/record not allowed
```

What you currently have in the branch https://github.com/curusarn/resh/tree/reduction needs to expose package content which will be used for communication (the record json)

**Comment by curusarn** [comment]
Should be fixed on https://github.com/curusarn/resh/tree/reduction
