### ISSUE TITLE
Unable to install it with sh

### ISSUE THREAD

**Issue by adamplansky** [curusarn/resh#192]
Since migration from `bash` to `sh` the installation script is failing for `dash` and `ash` shell interpreter. 

**Ubuntu**:
```
curl -fsSL https://raw.githubusercontent.com/curusarn/resh/master/scripts/rawinstall.sh | sh
sh: 3: set: Illegal option -o pipefail
```
**Alpine**:
```
curl -fsSL https://raw.githubusercontent.com/curusarn/resh/master/scripts/rawinstall.sh | sh

Please report any issues you encounter to: https://github.com/curusarn/resh/issues

Looking for the latest release ...
 * Latest version: 2.8.1 (git tag: v2.8.1)

Downloading files ...
 * resh_2.8.1_checksums.txt
######################################################################### 100.0%
 * resh_2.8.1_linux_amd64.tar.gz
######################################################################### 100.0%

Checking integrity ...
 * OK

Extracting downloaded files ...
 * OK
env: can't execute 'bash': No such file or directory
```

**Comment by curusarn** [comment]
Hi Adam,

Thanks for the report.
I have just removed the `pipefail` option since it's not POSIX: https://github.com/curusarn/resh/commit/7b4ae58552f55d791307bdaf370a76e6088b7f80

Let me know if the installation now works for you.

**Comment by adamplansky** [comment]
Hi Simon,
It seems like there are more problems.

Now I am getting: 
```
Looking for the latest release ...
rawinstall.sh: 27: Bad substitution
```

**Comment by curusarn** [comment]
Ok, I have changed the shell back to bash (https://github.com/curusarn/resh/commit/48b0ec4fe20c265d2991071de1bb1f3493bbef28).
I didn't realize that the variable substitutions I'm using are bash-specific.

Thanks for reporting this.
