### ISSUE TITLE
Keep the $HOME clean

### ISSUE THREAD

**Issue by curusarn** [curusarn/resh#64]
It is definitely nice to keep $HOME clean either by default or have an option to do so.

Either:
1) Make the project path configurable.
1) Move it away from $HOME by default

**Comment by curusarn** [comment]
a suggestion from reddit

**Comment by curusarn** [comment]
Consider changing the install directory from `~/.resh` to `~/.local/resh`

**Comment by curusarn** [comment]
Make the project path configurable.

**Comment by ernierasta** [comment]
Wouldn't it be more standard to put it in `.local/share/resh`?

**Comment by curusarn** [comment]
Fixed via #140
