### ISSUE TITLE
How does fish handle directories in shell history?

### ISSUE THREAD

**Issue by curusarn** [curusarn/resh#65]
Fish does have directories in its history so it's almost certain that they use them for something.

I couldn't find it mentioned in the docs. I should do more research.

**Comment by mafrasi2** [comment]
When fish records a command, it checks whether any of its parameters are existing paths and if so, stores them in the history. The autocompletion can then prioritize commands with existing paths.

Unfortunately, the cwd is not recorded (https://github.com/fish-shell/fish-shell/issues/120).
