### ISSUE TITLE
Conflicte with noclobber option

### ISSUE THREAD

**Issue by SebastianMeisel** [curusarn/resh#74]
Solution:
change the lines 22 and 169 in hook.sh from:
 > ~/.resh/postcollect_last_run_out.txt 2>&1 || echo "resh-postcollect ERROR: $(head -n 1 ~/.resh/postcollect_last_run_out.txt)"

to

 >**|** ~/.resh/postcollect_last_run_out.txt 2>&1 || echo "resh-postcollect ERROR: $(head -n 1 ~/.resh/postcollect_last_run_out.txt)"

(Line 22 ofcourse just collect_last_run)

**Comment by curusarn** [comment]
Fixed in https://github.com/curusarn/resh/commit/dce959390c693539310f4d5794f8cf25b1045155

Can you test if it works for you now?

**Comment by SebastianMeisel** [comment]
Works – thank you, for your fast work!
