### ISSUE TITLE
Add "source ~/.bashrc" to install script

### ISSUE THREAD

**Issue by GoDzM4TT3O** [curusarn/resh#78]
I tried installing resh just now, but the commands `resh` and `reshctl` didn't work. I ran `source ~/.bashrc` and they work just fine.

My OS: Ubuntu 18.04LTS, everything up to date.

**Comment by curusarn** [comment]
Sourcing bashrc in the install script won't help. Sourcing adds resh and reshctl functions to the **current** shell session. When install script is executed bash spawns a new session so sourcing anything inside the install script only changes the new session and doesn't have effect on the original shell session.

**Comment by curusarn** [comment]
There is not much I can do other than instruct people to restart the terminal session after install or to reload their dotfiles. 

Resh does source itself again after you update it but this is not possible after the initial installation.
