### ISSUE TITLE
Deamon failed to start because of invalid json history file

### ISSUE THREAD

**Issue by curusarn** [curusarn/resh#84]
~Resh daemon can sometimes fail (e.g. getting SIGTERM from Ctrl+C on MacOS).~

~As of now, daemon will launch when new shell session starts (unless it's already running).~

~This is not very intuitive and we might want to launch/check the daemon on every prompt.~

~related: #83~

**Comment by polipones** [comment]
For me, daemon does not start with new shell session (Ubuntu WSL).
Always saying this:
![image](https://user-images.githubusercontent.com/61013387/74437802-13445780-4e69-11ea-837d-248f0c51083a.png)

**Comment by curusarn** [comment]
Hi @polipones, 

can you post the contents of `~/.resh/daemon.log`? You can use this command: `tail -n 50 ~/.resh/daemon.log`

**Comment by polipones** [comment]
Yep, here it is.
[resh_daemon_log.txt](https://github.com/curusarn/resh/files/4198785/resh_daemon_log.txt)

**Comment by curusarn** [comment]
Thanks.

It looks like some binary characters got written into `~/.resh_history.json` (It already happened to someone force shutting down their machine) and resh daemon is failing to start because it can't decode all the records from the history file.

**Comment by curusarn** [comment]
I will take care of this soon.

**Comment by polipones** [comment]
Ok, thank you.

**Comment by curusarn** [comment]
fixed in https://github.com/curusarn/resh/pull/85 (invalid history files is fixed dring daemon start up)

**Comment by curusarn** [comment]
@polipones Hi, are you using Linux or macOS?

**Comment by polipones** [comment]
This problem occured to me, when I was using WSL (Windows Subsystem for Linux) with Ubuntu.
