### ISSUE TITLE
reshctl update breaks CTRL+R-binding

### ISSUE THREAD

**Issue by maede97** [curusarn/resh#90]
After an update using `reshctl update` and a restart of a terminal session, the CTRL+R-keybindig is not cought anymore. It must be manually enabled again using `reshctl enable ctrl_r_binding_global`.

**Comment by curusarn** [comment]
Config is unfortunately not preserved during the update.

I have added a hotfix just now (in v2.5.19) that preserves enabled Ctrl+R during the update.

**Comment by curusarn** [comment]
Config file survives updates since `v2.5.21`.
